image:
  file: flow.Dockerfile
vscode:
  extensions:
    - "redhat.vscode-yaml"
    - "denoland.vscode-deno"
checkoutLocation: "."
workspaceLocation: "flow"
tasks:
  - name: Initialize Flow CLI
    init: /workspace/init.sh
    env:
      FLOW_SUPABASE_HOST: eyrcnmuzzyriypdajwdk.supabase.co
      FLOW_SUPABASE_ANON_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5cmNubXV6enlyaXlwZGFqd2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDg3NTA1NzksImV4cCI6MTk2NDMyNjU3OX0.y1OyXD3-DYMz10eGxzo1eeamVMMUwIIeOoMryTRAoco
  - name: Open Read Me
    command: gp open README.md